language: go

go:
  - 1.3
  - 1.4
  - 1.5.1
  - tip

before_install:
  - go get gopkg.in/check.v1
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/eacha/aps/tools/test

script:
  - ./.test-cover.sh